var characters = {
	'Fox': 'fox',
	'Falco': 'falco',
	'Marth': 'marth',
	'Sheik': 'sheik',
	'Jigglypuff': 'jigglypuff',
	'Peach': 'peach',
	'Ice Climbers': 'ic',
	'Captain Falcon': 'cf',
	'Pikachu': 'pikachu',
	'Samus': 'samus',
	'Dr. Mario': 'doc',
	'Yoshi': 'yoshi',
	'Luigi': 'luigi',
	'Ganondorf': 'ganondorf',
	'Mario': 'mario',
	'Young Link': 'yl',
	'Donkey Kong': 'dk',
	'Link': 'link',
	'Mr. Game & Watch': 'gw',
	'Roy': 'roy',
	'Mewtwo': 'mewtwo',
	'Zelda': 'zelda',
	'Ness': 'ness',
	'Pichu': 'pichu',
	'Bowser': 'bowser',
	'Kirby': 'kirby'
}